#!/bin/bash

echo "📋 Bolt The Word: Task Processing Workflow"
echo "========================================="
echo ""
echo "1. 📝 PLAN TASK"
echo "   - Understand the requirements."
echo "   - Create/Update task.md."
echo "   - Check for existing Knowledge Items (KIs)."
echo ""
echo "2. 🔨 IMPLEMENT TASK"
echo "   - Create a feature branch (e.g., feat/my-feature)."
echo "   - Write clean, maintainable code."
echo "   - Follow the project's style guide."
echo ""
echo "3. 🧪 TEST TASK"
echo "   - Verify changes locally (npm run dev)."
echo "   - Ensure no regressions."
echo "   - Check for linting errors."
echo ""
echo "4. 🚀 CREATE PR"
echo "   - Push branch to origin."
echo "   - Create Pull Request via GitHub CLI or Web."
echo "   - Request review."
echo ""
echo "✅ Ready to code!"
